live_config_reload = true
# save_to_clipboard = true
# "window.dynamic_title" = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x616e88"
blue = "0x81a1c1"
cyan = "0x8fbcbb"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xeceff4"
yellow = "0xebcb8b"

[colors.cursor]
cursor = "0xd0d0d0"
text = "0xd0d0d0"

[colors.normal]
black = "0x3b4252"
blue = "0x81a1c1"
cyan = "0x7aa2f7"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xe5e9f0"
yellow = "0xebcb8c"

[colors.primary]
background = "0x16161e"
foreground = "0xd0d0d0"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Victor Mono"
style = "Bold"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.normal]
family = "Victor Mono"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.6
title = "Alacritty@Shubham"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 6
y = 4
